### ISSUE TITLE
a crash-reports about 1.16.2

### ISSUE THREAD

**Issue by M3ngZ** [rikka0w0/LanServerProperties#4]
---- Minecraft Crash Report ----
// You're mean.

Time: 20-8-21 下午11:19
Description: Rendering screen

java.lang.NoSuchMethodError: net.minecraft.class_436.method_27535(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Lnet/minecraft/class_5348;III)V
	at net.minecraft.class_436.handler$zza000$render(class_436.java:583)
	at net.minecraft.class_436.method_25394(class_436.java:79)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_436.handler$zza000$render(class_436.java:583)
	at net.minecraft.class_436.method_25394(class_436.java:79)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_436
	Mouse location: Scaled: (295, 162). Absolute: (885.000000, 486.000000)
	Screen size: Scaled: (534, 300). Absolute: (1600, 900). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['MengZ_'/193, l='ClientLevel', x=946.19, y=78.00, z=-306.54]]
	Chunk stats: Client Chunk Cache: 729, 483
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,71,192), Chunk: (at 0,4,0 in 10,12; contains blocks 160,0,192 to 175,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 21595 game time, 9596 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:674)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7555147256 bytes (7205 MB) / 8388608000 bytes (8000 MB) up to 8388608000 bytes (8000 MB)
	CPUs: 6
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: HMCL 3.2.149
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, programer_art
	Current Language: 简体中文 (中国)
	CPU: 6x Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz

**Comment by rikka0w0** [comment]
Please try this build: https://github.com/rikka0w0/LanServerProperties/releases/tag/1.16.2_Fabric
and see if the problem persists
