### ISSUE TITLE
2024愚人节版本报错 Cannot invoke "net.minecraft.class_5676.method_32605(Object)" because "this.val$allowCommandsSelector" is null

### ISSUE THREAD

**Issue by Marcus-zh** [rikka0w0/LanServerProperties#42]
可以进游戏,但是如果点击局域网开放就闪退
日志如下
```
---- Minecraft Crash Report ----
// My bad.

Time: 2024-04-04 15:39:19
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5676.method_32605(Object)" because "this.val$allowCommandsSelector" is null
	at rikka.lanserverproperties.OpenToLanScreenEx$1.syncWidgetValues(OpenToLanScreenEx.java:115)
	at rikka.lanserverproperties.OpenToLanScreenEx.postInitShareToLanScreen(OpenToLanScreenEx.java:121)
	at net.minecraft.class_436.handler$zmm000$lanserverproperties$mimicForge_GuiPostInit(class_436.java:599)
	at net.minecraft.class_436.method_25426(class_436.java:85)
	at net.minecraft.class_437.method_25423(class_437.java:318)
	at net.minecraft.class_310.method_1507(class_310.java:1199)
	at net.minecraft.class_433.method_47898(class_433.java:154)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:453)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:211)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1364)
	at net.minecraft.class_310.method_1514(class_310.java:898)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at rikka.lanserverproperties.OpenToLanScreenEx$1.syncWidgetValues(OpenToLanScreenEx.java:115)
	at rikka.lanserverproperties.OpenToLanScreenEx.postInitShareToLanScreen(OpenToLanScreenEx.java:121)
	at net.minecraft.class_436.handler$zmm000$lanserverproperties$mimicForge_GuiPostInit(class_436.java:599)
	at net.minecraft.class_436.method_25426(class_436.java:85)
	at net.minecraft.class_437.method_25423(class_437.java:318)
	at net.minecraft.class_310.method_1507(class_310.java:1199)
	at net.minecraft.class_433.method_47898(class_433.java:154)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:453)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:211)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_433
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:453)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:211)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1364)
	at net.minecraft.class_310.method_1514(class_310.java:898)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Uptime --
Details:
	JVM uptime: 181.930s
	Wall uptime: 140.750s
	High-res time: 136.993s
	Client ticks: 2017 ticks / 100.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2581)
	at net.minecraft.class_310.method_54580(class_310.java:1005)
	at net.minecraft.class_310.method_1514(class_310.java:918)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Affected level --
Details:
	All players: 1 total; [class_746['Marcus'/6, l='ClientLevel', x=-332.08, y=57.00, z=249.87]]
	Chunk stats: 961, 195
	Level dimension: minecraft:overworld
	Level spawn location: World: (-419,63,308), Section: (at 13,15,4 in -27,3,19; chunk contains blocks -432,-64,304 to -417,319,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 4323 game time, 4323 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 156

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, lanserverproperties, file/PotatoTranslationFixed-beta1.0.03.zip, file/PCL2 Skin.zip

-- System Details --
Details:
	Minecraft Version: 24w14potato
	Minecraft Version ID: 24w14potato
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 374034112 bytes (356 MiB) / 1048576000 bytes (1000 MiB) up to 2684354560 bytes (2560 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4000
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MB): 2112.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 10.18.10.5161
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 17162.83
	Virtual memory used (MB): 6715.02
	Swap memory total (MB): 9434.60
	Swap memory used (MB): 393.67
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx2560m
	Fabric Mods: 
		customskinloader: CustomSkinLoader 14.19.1
		fabric-api: Fabric API 0.96.14+24w14potato
			fabric-api-base: Fabric API Base 0.4.39+80f8cf51bb
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.57+e9d2a72bbb
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.21+cda3b7ddbb
			fabric-block-api-v1: Fabric Block API (v1) 1.0.19+6dfe4c9bbb
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.7+80f8cf51bb
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.49+80f8cf51bb
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.10+80f8cf51bb
			fabric-command-api-v1: Fabric Command API (v1) 1.2.44+f71b366fbb
			fabric-command-api-v2: Fabric Command API (v2) 2.2.23+80f8cf51bb
			fabric-commands-v0: Fabric Commands (v0) 0.2.61+df3654b3bb
			fabric-content-registries-v0: Fabric Content Registries (v0) 6.0.15+9b3069f6bb
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.15+cda3b7ddbb
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.26+80f8cf51bb
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.10+cda3b7ddbb
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 18.0.1+cda3b7ddbb
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.65+cda3b7ddbb
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.7+cda3b7ddbb
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.5+109a837cbb
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.85+df3654b3bb
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.49+80f8cf51bb
			fabric-item-api-v1: Fabric Item API (v1) 6.0.1+9b3069f6bb
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.34+42c290b4bb
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.44+80f8cf51bb
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.42+df3654b3bb
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.2+9b3069f6bb
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.14+9b3069f6bb
			fabric-message-api-v1: Fabric Message API (v1) 6.0.9+109a837cbb
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.11+80f8cf51bb
			fabric-models-v0: Fabric Models (v0) 0.4.10+9386d8a7bb
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.6+9342ba64bb
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.0.1+9b3069f6bb
			fabric-particles-v1: Fabric Particles (v1) 2.0.1+7b70ea8abb
			fabric-recipe-api-v1: Fabric Recipe API (v1) 4.1.2+f628d018bb
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.11+9b3069f6bb
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.10+1172e897bb
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.10+80f8cf51bb
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.59+df3654b3bb
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.45+73761d2ebb
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 4.0.0+cda3b7ddbb
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.62+df3654b3bb
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.2+42c290b4bb
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 3.0.1+e9d2a72bbb
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.0.1+e9d2a72bbb
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.20+7b70ea8abb
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.68+e78eae2dbb
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.20+80f8cf51bb
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.3+dca74304bb
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.7+1172e897bb
		fabricloader: Fabric Loader 0.15.9
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		lanserverproperties: Lan Server Properties 1.12.1
		minecraft: Minecraft 1.20.5-alpha.24.12.potato
	Launched Version: 24w14potato-Fabric 0.15.9
	Launcher name: PCL
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Intel(R) HD Graphics 4000 GL version 3.2.0 - Build 10.18.10.5161, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, lanserverproperties, file/PotatoTranslationFixed-beta1.0.03.zip, file/PCL2 Skin.zip (incompatible)
	Current Language: zh_cn
	Locale: zh_CN
	CPU: 4x Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Marcus'/6, l='ServerLevel[新的世界]', x=-332.08, y=57.00, z=249.87]]
	Data Packs: vanilla, fabric, fabric-convention-tags-v1
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -8204498144435933221
```

**Comment by zhaoyangzs** [comment]
如何下载支持2024愚人节版本的mod

**Comment by zhaoyangzs** [comment]
我的情况一样，不过显示2024愚人节版本是1.20.5并不在目前最新版支持范围内

**Comment by rikka0w0** [comment]
> 我的情况一样，不过显示2024愚人节版本是1.20.5并不在目前最新版支持范围内

我这边工作太忙没空维护，刚升了1.21，于是跳了1.20.5和1.20.6，当然你提个pr移植回1.20.5和1.20.6我这边双手欢迎ww

**Comment by rikka0w0** [comment]
可以试试最新版本，支持1.20.5到1.21.4，如果还不行的话我再看看
